# yamllint disable rule:document-start
# yamllint disable rule:line-length
#
# To generate a public key from SSH host key, run:
#   sudo ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub
# To edit secrets.yaml, run:
#   SOPS_AGE_KEY=$(sudo ssh-to-age -private-key -i /etc/ssh/ssh_host_ed25519_key) sops secrets.yaml
keys:
  - &home age1yf6qufzs04ehgta7cnheengu9vcxyxkl2h0t6dazlprn7wkr5v4qn7fhtv
  - &work age1tllgpk9y8ph5x282apvr4387kh66er4zpmhua6a75eter6fn8exsytfrnu
creation_rules:
  - path_regex: secrets/common\.yaml
    key_groups:
      - age:
          - *home
          - *work
