# See https://starship.rs/config/
format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state\
$git_metrics\
$hg_branch\
$docker_context\
$container\
$haskell\
$java\
$rust\
$terraform\
$nix_shell\
$memory_usage\
$aws\
$env_var\
$custom\
$sudo\
$cmd_duration\
$status\
$username\
$hostname\
$time\
$direnv\
$line_break\
$jobs\
$shell\
$character\
"""

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = '[\$](bold white)'
error_symbol = '[\$](bold white)'

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'bold blue'
truncation_length = 10
truncate_to_repo = false

[direnv]
disabled = false
format = '[$allowed]($style) '
symbol = ''
allowed_msg = ''
loaded_msg = ''
not_allowed_msg = 'direnv not allowed'
unloaded_msg = 'direnv not loaded'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
symbol = ' '
style = 'green'

[git_commit]
format = '[\($hash$tag\)]($style)'
style = 'green'
tag_disabled = false
only_detached = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style)) '
conflicted = '❎'
ahead = '🔼'
behind = '🔽'
diverged = '🤸(↑$ahead_count↓$behind_count)'
up_to_date = '✅'
untracked = '🤔'
stashed = ''
modified = '🎨'
staged = '💨'
renamed = '🎨'
deleted = '🚮'
style = 'green'

[hg_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
disabled = false

[container]
format = '[\[$name\]]($style) '

[git_state]
format = '[\($state( $progress_current/$progress_total)\)]($style) '
style = 'green'

[nix_shell]
format = '[$symbol$state]($style) '
disabled = true

[lua]
disabled = true

[cmd_duration]
format = '[took $duration]($style) '
style = 'dimmed white'

[status]
disabled = false
format = '[$symbol $status]($style) '

[username]
format = '[$user]($style)'
show_always = true
style_user = 'dimmed white'

[hostname]
format = '[@$ssh_symbol$hostname ]($style)'
ssh_only = false
style = 'dimmed white'

[time]
disabled = false
format = '[\[$time\]]($style) '
style = 'dimmed white'

# Disabled
##########

[aws]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[fill]
disabled = true

[fortran]
disabled = true

[gcloud]
disabled = true

[gleam]
disabled = true

[golang]
disabled = true
