# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "nvme" "uas" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Crucial T500 (nvme, LABEL=nixos-root). Moved off the TEAM TM8FP6001T, whose
  # DRAM-less Realtek controller stalls ~24ms on the first read after >=0.5s idle.
  # Old root (192a4b3e-dd0f-4690-a241-b18c821df301) is still intact on the TEAM
  # drive and remains bootable via older generations.
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/09d78172-4c27-4922-9eb3-8eaa0eaa8536";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/3D7C-0794";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
}
